hparams:
  lr: 0.001
  batch_size: 4
  optimizer: 'Adam'
  binary: True
  max_step: 100
  valid_step: 10
data:
  root: 'data_test'
  train_split: 'libri-test'
  eval_split: 'libri-test'
  num_mels: 23
  use_energy: False
model:
  num_layers: 2
  bias: False
  hidden_size: 512
  bidirectional: True