data:
  root: 'data_test'
  split: 'test-clean'
  num_mels: 23
  use_energy: False
model:
  binary: True
  linear_proj: 3
  num_layers: 1
  bias: False
  hidden_size: 512
  bidirectional: True
decoder:
  lm: 'lm/librispeech/2gram.bin'