hparams:
  lr: 0.001
  batch_size: 4
  optimizer: 'Adam'
  binary: True
  max_step: 1000000
  valid_step: 100
data:
  root: 'data_test'
  train_split: 'test-clean'
  eval_split: 'test-clean'
  num_mels: 23
  use_energy: False
model:
  linear_proj: 1
  num_layers: 1
  bias: False
  hidden_size: 512
  bidirectional: True
  dropout: 0.1