hparams:
  lr: 0.001
  batch_size: 4
  num_epochs: 100
  optimizer: 'Adam'
  binary: False
  valid_step: 100
data:
  root: 'data_test'
  train_split: 'libri-test'
  eval_split: 'libri-test'
  num_mels: 23
  use_energy: False

model:
  num_layers: 4
  bias: False
  hidden_size: 512
  bidirectional: True

  